### ISSUE TITLE
Add dbGaP consent_code to output

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/dbgap_xml_parser#1]
We need both the dbGaP consent abbreviation (eg HMB-IRB-NPU) and the code that goes with that consent (eg, c1, c2, etc). Is it possible to get the code out of the dbGaP xml? If not, where would we get the code->abbreviation mapping?

**Comment by smgogarten** [comment]
The consent code is not in the XML, and the only place I know to get it is in the data dictionary for the subject-consent file.

**Comment by amstilp** [comment]
Ok. We should figure out a streamlined way to get it. Maybe we could grab the data dictionary from the FTP site?

**Comment by amstilp** [comment]
I was leaving this open with the idea that I could modify the code to pull the data dictionary from the FTP site, once I get sick of looking up the consent codes. Can we reopen?

**Comment by amstilp** [comment]
nevermind you updated it :D
